# Generated by Django 5.2.8 on 2025-11-21 13:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de impuesto a aplicar (ej: 21.00 para 21%)', max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('tax_included', models.BooleanField(default=False, help_text='Si está activado, los precios mostrados ya incluyen impuestos', verbose_name='Impuesto Incluido en Precio')),
                ('receipt_header', models.TextField(blank=True, help_text='Texto que aparece al inicio del recibo (nombre negocio, dirección, etc.)', verbose_name='Encabezado del Recibo')),
                ('receipt_footer', models.TextField(blank=True, help_text='Texto que aparece al final del recibo (mensaje, horarios, etc.)', verbose_name='Pie del Recibo')),
                ('auto_print', models.BooleanField(default=False, help_text='Imprimir recibo automáticamente al completar venta', verbose_name='Imprimir Automáticamente')),
                ('allow_cash', models.BooleanField(default=True, verbose_name='Permitir Efectivo')),
                ('allow_card', models.BooleanField(default=True, verbose_name='Permitir Tarjeta')),
                ('allow_transfer', models.BooleanField(default=False, verbose_name='Permitir Transferencia')),
                ('require_customer', models.BooleanField(default=False, help_text='Obligatorio seleccionar cliente para cada venta', verbose_name='Requiere Cliente')),
                ('allow_discounts', models.BooleanField(default=True, verbose_name='Permitir Descuentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Configuration',
                'verbose_name_plural': 'Sales Configuration',
                'db_table': 'sales_config',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Venta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Impuesto')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('mixed', 'Mixto')], default='cash', max_length=20, verbose_name='Método de Pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Pagado')),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cambio')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Cliente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sales_sale',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sales_sale_created_66311a_idx'), models.Index(fields=['sale_number'], name='sales_sale_sale_nu_99d8fe_idx'), models.Index(fields=['status'], name='sales_sale_status_532843_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID del Producto')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Línea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
                'db_table': 'sales_saleitem',
                'ordering': ['id'],
            },
        ),
    ]
