# Generated by Django 5.2.8 on 2025-11-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Empleado')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10, verbose_name='Estado')),
                ('initial_amount', models.DecimalField(decimal_places=2, help_text='Fondo de caja al abrir', max_digits=10, verbose_name='Monto Inicial')),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado al cerrar', max_digits=10, null=True, verbose_name='Monto Final')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado: inicial + ventas + entradas - salidas', max_digits=10, null=True, verbose_name='Monto Esperado')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='Final - Esperado (positivo = sobrante, negativo = faltante)', max_digits=10, null=True, verbose_name='Diferencia')),
                ('opening_notes', models.TextField(blank=True, verbose_name='Notas de Apertura')),
                ('closing_notes', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
            ],
            options={
                'verbose_name': 'Caja Registradora',
                'verbose_name_plural': 'Cajas Registradoras',
                'db_table': 'sales_cashregister',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['-opened_at'], name='sales_cashr_opened__c57c6b_idx'), models.Index(fields=['status'], name='sales_cashr_status_ca0b0d_idx')],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.cashregister', verbose_name='Caja'),
        ),
        migrations.CreateModel(
            name='ParkedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=30, unique=True, verbose_name='Número de Ticket')),
                ('cart_data', models.JSONField(help_text="Carrito serializado: {items: [...], payment_method: '', notes: ''}", verbose_name='Datos del Carrito')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Empleado')),
                ('notes', models.TextField(blank=True, help_text="Notas adicionales sobre el ticket (ej: 'Cliente volvió por más productos')", verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Parking')),
                ('expires_at', models.DateTimeField(help_text='Tickets expirados se eliminan automáticamente', verbose_name='Expira el')),
            ],
            options={
                'verbose_name': 'Ticket Aparcado',
                'verbose_name_plural': 'Tickets Aparcados',
                'db_table': 'sales_parkedticket',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sales_parke_created_b35b76_idx'), models.Index(fields=['expires_at'], name='sales_parke_expires_5f298e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('reason', models.CharField(help_text="Razón del movimiento (ej: 'Pago a proveedor', 'Reposición fondo')", max_length=255, verbose_name='Motivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Empleado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sales.cashregister', verbose_name='Caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'sales_cashmovement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sales_cashm_created_c0af9d_idx'), models.Index(fields=['type'], name='sales_cashm_type_1ed45f_idx')],
            },
        ),
    ]
