# Generated by Django 5.2.8 on 2025-11-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_cashregister_sale_cash_register_parkedticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesconfig',
            name='auto_print',
        ),
        migrations.RemoveField(
            model_name='salesconfig',
            name='receipt_footer',
        ),
        migrations.RemoveField(
            model_name='salesconfig',
            name='receipt_header',
        ),
        migrations.RemoveField(
            model_name='salesconfig',
            name='tax_included',
        ),
        migrations.RemoveField(
            model_name='salesconfig',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='enable_parked_tickets',
            field=models.BooleanField(default=True, help_text='Permitir aparcar tickets (guardar carrito temporalmente)', verbose_name='Habilitar Tickets Aparcados'),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='allow_card',
            field=models.BooleanField(default=True, help_text='Habilitar tarjeta como método de pago', verbose_name='Permitir Tarjeta'),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='allow_cash',
            field=models.BooleanField(default=True, help_text='Habilitar efectivo como método de pago', verbose_name='Permitir Efectivo'),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='allow_discounts',
            field=models.BooleanField(default=True, help_text='Permitir aplicar descuentos en el POS', verbose_name='Permitir Descuentos'),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='allow_transfer',
            field=models.BooleanField(default=False, help_text='Habilitar transferencia bancaria como método de pago', verbose_name='Permitir Transferencia'),
        ),
    ]
