# Generated by Django 5.2.8 on 2025-11-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_salesconfig_auto_print_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default='Unknown', help_text='Nombre del empleado que tiene el carrito activo', max_length=255, verbose_name='Empleado')),
                ('cart_data', models.JSONField(default=dict, help_text='Items del carrito en formato JSON', verbose_name='Datos del Carrito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Carrito Activo',
                'verbose_name_plural': 'Carritos Activos',
                'db_table': 'sales_active_cart',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['employee_name'], name='sales_activ_employe_df0e1d_idx'), models.Index(fields=['-updated_at'], name='sales_activ_updated_67c440_idx')],
            },
        ),
    ]
