# Generated by Django 5.2.8 on 2025-11-24 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_uuid'),
        ('sales', '0004_activecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.localuser', verbose_name='Empleado'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user', '-created_at'], name='sales_sale_user_id_0f12d8_idx'),
        ),
    ]
