# Generated by Django 6.0 on 2025-12-24 12:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_user_sale_sales_sale_user_id_0f12d8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown by tax rate for multi-tax invoicing', verbose_name='Desglose de Impuestos'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_service',
            field=models.BooleanField(default=False, help_text="Services don't affect stock", verbose_name='Es Servicio'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount before tax', max_digits=10, verbose_name='Importe Neto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount for this item', max_digits=10, verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_class_name',
            field=models.CharField(blank=True, help_text='Tax class name for historical reference', max_length=100, verbose_name='Nombre del Tipo de Impuesto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate applied to this item', max_digits=5, verbose_name='Tasa de Impuesto (%)'),
        ),
    ]
